### ISSUE TITLE
Go To and Zone cleaning not working anymore

### ISSUE THREAD

**Issue by TinusScheppers** [LazyT/rrcc#12]
It seems that the coordinates of zones and Go To's are incorrect.
When navigating to the zone/GoTo the vacuum always gets lost.

I recently installed the latest version of Valetudo (0.3.1) and downloaded the latest release of RRCC (to get the map working again) but ever since I can't seem to retrieve/use the correct coordinates.

**Comment by LazyT** [comment]
Use the swap options in the map context menu.

**Comment by TinusScheppers** [comment]
> 
> 
> Use the swap options in the map context menu.

Indeed, it seems I needed to check the swap left/right option.
Now GoTo/Zones and configured zones work again!

Was this some kind of new features? As I did not need to enable this previously?

Thanks for the quick reply!

**Comment by LazyT** [comment]
Valetudo changes, option was already there but not needed yet.

**Comment by MickL** [comment]
I also had the same problem: All map coordinates were totally off no matter if i set go-to, virtual wall, or zone. After right clicking on the map and selecting swap -> swap left/right it works fine.

Firmware: 3.3.9
Firmware build: 001864
Valetudo: 0.3.1
rrcc: 0.8.6
