### ISSUE TITLE
No Go zones Not working

### ISSUE THREAD

**Issue by cm86** [LazyT/rrcc#13]
Hello i have created 2 No-Go zones.
But my Roborock doesn't detect them.
What data so you need from me to figure Out what's wrong!?

**Comment by LazyT** [comment]
What means "doesn't detect it"?

Is it shown in RRCC as red line/polygon? Any errors when creating it?

Roborock gen2 with firmware >= 1633 and Valetudo >=0.3.1 installed?

First of all make sure that GoTo is working correctly. If not play around with the swapping options in map context menu. With Valetudo 0.3.1 I've to enable swap left/right.

**Comment by cm86** [comment]
Hello again,
Firmware is 001748
valetudo is 0.3.1

And you aree right...
swaping left/right printed the zones at the right place...
This was the first state in rrcc...
![Bildschirmfoto 2019-05-25 um 13 52 38](https://user-images.githubusercontent.com/14919688/58369044-4454b480-7ef5-11e9-81fc-76e2eff33d89.png)
and now they at the right place...
![Bildschirmfoto 2019-05-25 um 13 58 51](https://user-images.githubusercontent.com/14919688/58369049-56365780-7ef5-11e9-88bd-16fe0f5ca777.png)
Thanks for the hint...

What do you mean, when can we edit this things in valetudo...? :)

**Comment by LazyT** [comment]
I don't know, you have to ask the Valetudo devs... :wink:
