### ISSUE TITLE
Generation 3 support

### ISSUE THREAD

**Issue by megapearl** [LazyT/rrcc#15]
Hi,

I really love your software, are there any future plans to support the gen3 roborock series?
I'm using your software on linux to control my Xiaomi Roborock T65 (gen3) vacuum cleaner.
Only thing is I don't see any heat map created, controls and sensors are working fine though.
I live in Europe and need to change my phone first to chinese timezone then connect with their official iOS app to the vacuum cleaner, and then your software can connect using the token to the T65 but the token times out after a couple of hours and need to repeat the procedure.
I like to change the chinese firmware (T6*) to the worldwide firmware (S6*) any idea how to get that firmware and replace it?

Best Regards,
Donald.

**Comment by LazyT** [comment]
No, sorry. I don't own a g3 and doesn't read about it.
