### ISSUE TITLE
Having trouble updating Valetudo

### ISSUE THREAD

**Issue by jbgtenn** [LazyT/rrcc#16]
![Capture](https://user-images.githubusercontent.com/33166657/59205525-1ae08d80-8b71-11e9-9a57-f7c148705144.PNG)

I have 0.2.3 version installed currently but not able to update it within the app to latest version.

**Comment by LazyT** [comment]
Don't know what the problem is, but upgrade from 0.2 to 0.3 is tricky. Much has changed (dummycloud integrated into valetudo).

It's better to build a clean new firmware image.
