### ISSUE TITLE
Search firmware how?

### ISSUE THREAD

**Issue by bruvv** [LazyT/rrcc#17]
There is a search function to find new firmware versions but it is no where documented with examples on how to use it. Can someone explain me how this search function works?

**Comment by LazyT** [comment]
An example/documentation for this, really? Are the tooltips not enough?

Select your model and set the start/stop version for the range to search in, for example from 1700 to 1800 for gen2. That's all.

Choosing another server can change the results.

If the name of the firmware change you can edit the name too, like "v11_00????.pkg" for older versions.

The "????" will always be replaced by the current searched version automatically.

Hope this helps...

**Comment by bruvv** [comment]
For me the tooltips are not very useful. will be more useful when default numbers will be filled in:
![image](https://user-images.githubusercontent.com/3063928/59563501-3baa5680-903b-11e9-863e-30a305b9946e.png)
This gives 0 stuff

**Comment by LazyT** [comment]
Of course there is 0 result when you search for a firmware version 17, try 1700.

**Comment by bruvv** [comment]
Ah now I get it! I thought the left (where I filled in 17) filled in the ???? as: 1700 ;) now I know that it should be 1700. Thanks!
