### ISSUE TITLE
Koordinatensystem falsch?

### ISSUE THREAD

**Issue by Trrw** [LazyT/rrcc#19]
Hallo,

wenn ich eine Zone anlege und diese dann starten möchte, fährt der Roboter in eine komplett andere Richtung. Für mich macht es den Anschein, dass das Koordinatensystem falsch gelegt ist. Ein Karte drehen hat keinen erfolg gebracht, da sich auch das Koordinatensystem mitdreht.

**Comment by LazyT** [comment]
Dafür ist die Tauschen Option, aktiviere mal links/rechts und richte die Zone neu ein.
