### ISSUE TITLE
Connection timeout. v3.3.9_003357

### ISSUE THREAD

**Issue by marvinwankersteen** [LazyT/rrcc#2]
I installed the rooted firmware 3.3.9_003357 on vacuum.v1 and a connection can not be established. I deleted the config already in .rrcc/ and tried with a new one.
The map is displayed from Valetudo.
I use the AppImage 0.71.

Is there an issue with this version?

**Comment by LazyT** [comment]
I don't have an v1.

Maybe they changed something in the communication if you are sure your token is correct.

**Comment by marvinwankersteen** [comment]
You are right, the token was the problem.
Yesterday, in the night, I used this wrong one:
```
cat /mnt/data/miio/device.token | xxd -p
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx360a
```

Today, after sleeping, this:
```
printf $(cat /mnt/data/miio/device.token) | xxd -p
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx36
```

The different is the new line character, I think.

It's working now.
Thanks for the hint ;-)

**Comment by LazyT** [comment]
Why not use the token extractor in rrcc?

**Comment by marvinwankersteen** [comment]
I didn't thought about and the private key is only added in ssh-agent via KeePassXC.
