### ISSUE TITLE
KeyAuthenticationFailedError

### ISSUE THREAD

**Issue by momo42** [LazyT/rrcc#23]
Hi @LazyT ,

yesterday I installed Valetudo 0.4.0 (factory reset + fresh install) on my Mi Vacuum Gen1.
Everything went fine. Also terminal ssh access via key works well.

After that I tried rrcc 0.8.7 (and also 0.8.6) but sadly it isn't able to authenticate. So I had to copy paste my token by hand. RRCC works now but every time I try to get valetudo or firmware version I get the same error message again. I'm unsure whats the problem because accessing the robot via terminal works fine.

During Valetudo setup I used `ssh-keygen -t ed25519` to generate a separate ssh key without a passphrase. It lies in `/home/momo42/.ssh/id_ed25519_robi` and is recognized by rrcc without errors.

Do you have any idea whats wrong here?

Aside from that I like rrcc very much. Thank you for this nice piece of software!

edit: FW is v11_003468

edit2: no idea if its relevant but for temrinal access I type `ssh -i .ssh/id_ed25519_robi root@192.168.179.23`

edit3: Also tried to set a passphrase for the key and providing it in rrcc. Same result.

**Comment by LazyT** [comment]
Looks like ed25519 is supported >= 0.7.0 of libssh.

Unfortunately rrcc for linux comes with 0.6.3 (build system is ubuntu 16.04 for downward compatibility).

I will look at this...

**Comment by LazyT** [comment]
Please redownload 0.8.7 and try again.

**Comment by momo42** [comment]
You are my hero! :-)
Works like a charm. Never expected such a fast fix! Way better support as with paid software. :-D
I've bought you a virtual beer for thanks.
Keep up this nice project!

**Comment by LazyT** [comment]
Thanks for the :beer:
