### ISSUE TITLE
AppImageD -> AppImageLauncher?

### ISSUE THREAD

**Issue by momo42** [LazyT/rrcc#24]
Hi @LazyT,

just stubled upon this quite new application: https://github.com/TheAssassin/AppImageLauncher

Might be a better recommendation than AmmImageD. Have a look at it! I'll also try it now.
In fact RRCC is the first AppImage I came across.

**Comment by momo42** [comment]
I have to say that under Linux Mint 19.1 the gui of AppImageLauncher is kinda broken. I'm not able to see the config checkboxes. On Linux Mint I would not recommend it. But I also tested in a Ubuntu vm without errors. Aside from this Linux mint specific gui bug AppImageLaunchers' approach seems to be more resource-efficient and comprehensible than running a daemon all the time, that moves downloaded files around on its own.

**Comment by LazyT** [comment]
Works fine with debian buster and replaced appimaged here, thanks for the hint.

Added to the readme.
