### ISSUE TITLE
Support more than 1 device

### ISSUE THREAD

**Issue by Sonderstorch** [LazyT/rrcc#26]
Hi there,

it would be rather nice, if the UI could support more than one device; or at least could be started with an option giving it a different config file for each robot. This way more than one instance could be used at the same time.

**Comment by LazyT** [comment]
I don't think there are many users with more than 1 robot.

As workaround you can make several rrcc dirs and put a config into these directories instead of the home directory.

**Comment by Sonderstorch** [comment]
Ok, I see. If a rrcc.cfg is within the same directory as rrcc.exe it picks up that instead of the  %HOMEPATH%\.rrcc\rrcc.cfg one. Good to know, thanks!

All that's left would be a command line option to specify rrcc.cfg which could be set in the desktop shortcut (assuming Windows). I'll leave that issue open; but you can close it if you wish.

**Comment by LazyT** [comment]
Parameter "-c" or "--config" added to set a config file via command line.
