### ISSUE TITLE
Support Web Auth valetudo

### ISSUE THREAD

**Issue by RunGp** [LazyT/rrcc#27]
Hi

I set a password for protecting web interface of valetudo
All function works fine execpt map is not show in rrcc  " Host require authentication"
SSH key is set but i dont find where set web auth ?
Bug ? Not support by rrcc ? or i miss something ?

Thanks

**Comment by LazyT** [comment]
Oh, didn't realized valetudo has auth now.

It's not supported yet.

**Comment by RunGp** [comment]
yep valetudo beta 0.4.0 add basic auth function :)
https://github.com/Hypfer/Valetudo/releases/tag/0.4.0

Thanks

**Comment by LazyT** [comment]
It's now supported.
