### ISSUE TITLE
version number information missing on macOS

### ISSUE THREAD

**Issue by core-code** [LazyT/rrcc#28]
i've downloaded Version '0.8.7' but when selecting it in the Finder and using 'Get Info' (or QuickLook, or ColumnView) it doesn't show any Version-number at all. i guess the *CFBundleVersion* and *CFBundleShortVersionString* entries in your Info.plist file are missing.

all apps on macOS are supposed to contain valid version information.

furthermore, even if your app had valid version information, you wouldn't see it because your Info.plist has the 'CFBundleGetInfoString' key that has been deprecated for more than 10 years. it should be removed.

**Comment by LazyT** [comment]
Thanks for the hint, I'm not a Mac user. :wink:

The Info.plist is the default Qt5 creates.

It's easy to automatically add the version number, something else (besides CFBundleIdentifier) to improve here?

**Comment by core-code** [comment]
not really sure about anything Qt related, but from what i gather you should be able to just add
VERSION = 0.8.7
to your "rrcc.pro" file. this should even add the version number for Windows too i guess.

post-processing the finished build with /usr/libexec/PlistBuddy could be another option

**Comment by LazyT** [comment]
Done!
