### ISSUE TITLE
Why is the Qt style hardcoded? 

### ISSUE THREAD

**Issue by Fuchs** [LazyT/rrcc#32]
In mainwindow.cpp you set
 QApplication::setStyle("Fusion");

which will hardcode the QtStyle to fusion, overriding both the system default and the command line argument. 

Is there a specific reason to do this? This will make the application look out of place on every supported platform, whilst Qt would, in most cases, otherwise use the platform style so that the application looks like every other application.

Aside from that: very nice application, thank you :)

**Comment by LazyT** [comment]
> Is there a specific reason to do this?

Yes, on one of the 3 (win/lin/mac) there was a problem with the native style - but I can't remember what exactly.
