### ISSUE TITLE
Provide release for new features

### ISSUE THREAD

**Issue by fredless** [LazyT/rrcc#34]
With the prevalence of valetudo 0.4.0 out there now, new builds with http auth support would be gratefully accepted - if only to keep folks from pulling their hair out before they notice #27 and #28.

**Comment by LazyT** [comment]
Yes, you are right.

Unfortunately my buildsystem fucked up some months ago.

**Comment by LazyT** [comment]
Done!

**Comment by fredless** [comment]
very much appreciated!
