### ISSUE TITLE
Valetudo RE detection failed

### ISSUE THREAD

**Issue by mayonezo** [LazyT/rrcc#35]
I am running the fork Valetudo RE 0.8.2 on my Roborock S55. When I try to check the Valetudo version via rrcc 0.8.7, I get a popup, reading:
```
Valetudo detection failed:

got empty response
```
Is Valetudo RE not supported or is something wrong with my settings?

**Comment by LazyT** [comment]
Version detection is done via "fgrep -a -m1 -A1 '\"name\": \"valetudo\"' /usr/local/bin/valetudo".

If this doesn't work for re you get the above error.

**Comment by zvldz** [comment]
"fgrep -a -m1 -A1 '"name": "valetudo'"
works on all versions

**Comment by LazyT** [comment]
Fixed, Thanks!

**Comment by evanre** [comment]
Hi, @LazyT may I ask you to build a fresh version with the latest fixes? I've tried to do it by my self but I got libs errors during making it on my mac :(
