### ISSUE TITLE
How to use RRCC without root

### ISSUE THREAD

**Issue by mamartins** [LazyT/rrcc#37]
Hello,

I've a brand new RoboRock, which hasn't been connected to the Internet yet. Can I use RRCC without connecting it to the internet and without rooting the Roborock?
I've tried to follow the app instructions but other than connecting to RoboRock wifi, I did not understood the steps.

**Comment by LazyT** [comment]
It's clearly stated on the startpage which functions are not available without root. You don't need to root but miss some functions (like map).

You always need the device token. Please read for example https://github.com/Maxmudjon/com.xiaomi-miio/blob/master/docs/obtain_token.md to understand the required the steps.

**Comment by mamartins** [comment]
Yes, but the process is not clear, how it is written on the rrcc, after I connect to the roborock wifi, it looks like he can gather the token. 
Is the token available before setting up the roborock or I need to connect it to the internet at least once?

thanks
