### ISSUE TITLE
Configure zones for Valetudo

### ISSUE THREAD

**Issue by Nebukadneza** [LazyT/rrcc#4]
Hi,

rrcc is super convenient when you currently have access to a PC. However, sometimes the smartphone is just more convenient — and Valetudo is a good way to control the vac via smartphone.

Since coordinate-selection for zone cleanup is more convenient in rrcc, would it be possible to convert the coordinates into the coordinate-system valetudo uses? Any maybe as an extra, use SSH (which you already have!) to write `/etc/valetudo/config.json`? Or at least spout out the coordinates for copy-pasting into valetudo by the user?

Thanks for your great tool, and thanks even more for making FOSS for this little robo ^_^.
Best,
-Dario

**Comment by LazyT** [comment]
I don't know which coordinate system valatudo has. 

When this feature is missing it should be better implemented in valetudo directly and not external tools.

**Comment by Nebukadneza** [comment]
Hi,

while i agree that this is a feature needed in both systems in the future, i still think it would be convenient if both could interoperate.
For reference, here
https://github.com/Hypfer/Valetudo/blob/1f0450c1fe13aeb987395260af123824041ed875/miio/Vacuum.js#L373
is a note that explains the coordinate-system used by Valetudo. This is also the coordinates returned by the API, for example.

If i find some time, I’d like to contribute basic interoperability soon, because i still think the UI of rrcc with the convenience of valetudo make a great pair ^_^. Would you mind leaving the issue open for a while?

Best,
-Dario

**Comment by muuuh** [comment]
To my understanding, to get from RRCC to Valetudo coordinates, you have to do:
    [RRCC coordinates] - 25500 = [Valetudo coordinates]

**Comment by Monkeyinapocket** [comment]
Hi, i created a small python script to convert the RRCC Zones in Valetudo configuration files. It works for me so it should also satisfy your needs.
