### ISSUE TITLE
Humble Suggestion to integrate Valetudo RE

### ISSUE THREAD

**Issue by WonderDoge** [LazyT/rrcc#42]
Dear LazyT,

This tool is awesome, many thanks for creating it! Unfortunately latest versions of Valetudo do not represent the map that well anymore; for me, the map is actually not refreshed anymore in the Web API or RRCC, there is just the vacuum icon. I rebuilt Valetudo many times and also used their auto-build webpage, but the issue persist. Also, I cannot access the vacuum via SSH anymore. (Of course, I brought this to their attention and they are working on it. I mean, they did and do really great things.)

As I cannot fix this myself, but need that map working, I switched to Valetudo RE (https://github.com/rand256/valetudo), which works perfectly and has even some other features (e.g. telegram integration). As I also really like RRCC, I would like to ask humbly you whether it would be possible for you to integrate the option to download Valetudo RE into RRCC (via the Valetudo download/update dialogue).

Of course, I know that I am in no position to request anything as you are the creator and as you may have better things to do. I hope not to have been impertinent and thank you for your consideration.

**Comment by LazyT** [comment]
The code was ready long time ago but never published because Valetudo RE map can't be displayed.

Since Valetudo 0.6 map can't be displayed too because of changed format, so it's fair to add it now... ;-)

**Comment by WonderDoge** [comment]
> The code was ready long time ago but never published because Valetudo RE map can't be displayed.
> 
> Since Valetudo 0.6 map can't be displayed too because of changed format, so it's fair to add it now... ;-)

Many many thanks. :D
