### ISSUE TITLE
No map is displayed

### ISSUE THREAD

**Issue by dkm** [LazyT/rrcc#6]
I have built rrcc from source.
I think I have all the UI working, except for the map that I can't seem to display.

Its works fine with valetudo (ie. the map is created correctly when the robot moves).
I've tried to start the cleaning from rrcc, but even if everything seems to work fine, no map is displayed.

**Comment by LazyT** [comment]
WIN/LIN/OSX?

What means "no map is displayed"? Have you enabled the map view via toolbutton?
Refreshes the progressbar on bottom all 5 seconds?
Does it work with the release binary?

**Comment by dkm** [comment]
I'm using Debian GNU/Linux.
I think the issue is that I have not «enabled the map view via toolbutton». I guess I've missed it, even thought I've spent some time trying all the buttons I could find in the UI. Which one is it ?

**Comment by LazyT** [comment]
The 3. from left called "Map/Show Map"?

**Comment by dkm** [comment]
Sorry, I don't understand how I could not see it before. Works fine, sorry for the noise !

**Comment by kreativmonkey** [comment]
I have the same issue but have called "Map/Show Map" Button on the GUI. 

I have installed Valetudo 0.3.1 and have no Problems in the Webfrontend. But on RRCC i can't see the Map only the Vaccuum Icon. The Refresh Button can't help out. Is there another setting?

**Comment by LazyT** [comment]
RRCC renders the map from "http://<robot>/api/map/latest".

Check the output in your webbrowser, if there is no valid map data RRCC can't show the map.

**Comment by kreativmonkey** [comment]
There is a big json under <robot-ip>/api/map/latest looks like this:

```{"header_length":20,"data_length":53903,"version":{"major":1,"minor":0},"map_index":24,"map_sequence":3117,"image":{"position":{"top":329,"left":246},"dimensions":{"height":303,"width":385},"pixels":{"floor":[[108,261],[108,258],[108,256],[108,255]```

**Comment by LazyT** [comment]
You can send me the json via e-mail to check here.

**Comment by HorizonKane** [comment]
Hi,

I have the same issue.

when I activate the map view, I see a blue banner saying NO MAP DATA. However when I access the link I find a JSON with many numbers, too.
