### ISSUE TITLE
SSH Key

### ISSUE THREAD

**Issue by DrJeff** [LazyT/rrcc#8]
When trying to use SSh key I get a dialog box saying "Does not look like valid private key!" This is the key used from ssh client to the vacuum. I'm running on macOS, I also tried on Windows 10 with the same message? any Ideas of why?
Can I force the keyfile?

**Comment by LazyT** [comment]
Please convert your key to the open ssh format.

**Comment by DrJeff** [comment]
I believe it already is. Generated via the Roborock directly and just copied. Is there any extension that is required to work?  Currently it is `vacuum_key`

**Comment by LazyT** [comment]
It checks only for "-----BEGIN RSA PRIVATE KEY-----" and "-----END RSA PRIVATE KEY-----", it's the openSSH "old" format.

**Comment by DrJeff** [comment]
It's weird it will not take the Key in that format but I tried another Key from another system and that will go but it's the wrong key of course. I will set a username and password and not worry too much.

**Comment by JST2018** [comment]
Hi there,

I'm stuck on the same thing here... I've created a SSh-key like it was stated on the manual to enable ssh on the roborock. Now I have a openssh key starting with "ssh-rsa ABCDEFG..." I have no clue how to convert it to the old format or create a new one with that format...

What should I do now?

Regards,
JST

**Comment by fredless** [comment]
S5 vac with Valetudo 0.4.0 and firmware 3.3.9.001886 installed, RRCC 0.8.7 on Windows.  

I had this issue too and I was never able to get it sorted, other than to resort to the same workaround as @DrJeff mentioned.

**Comment by hispeedsurfer** [comment]
I had the same problem and solved it converting the key with the following command.

`ssh-keygen -p -m PEM -f ~/.ssh/id_rsa`

**Comment by gipnokote** [comment]
> It checks only for "-----BEGIN RSA PRIVATE KEY-----" and "-----END RSA PRIVATE KEY-----", it's the openSSH "old" format.

This is exactly the problem. It checks for LF at the end of these strings, while when save on Windows it can be CRLF, and your check fails. Also, the ending line can be without LF or CRLF at all.

**Comment by LazyT** [comment]
Checking only for "PRIVATE KEY" now, thanks.
